#!/usr/bin/env bash

# This script display 'best school" but an exception for 9th iteration

counter=1
while [ $counter -le 10 ]
do
  if [ $counter -eq 9 ]
  then
    echo 'Hi'
  fi
  echo "Best School"
  ((counter++))

done
