#!/usr/bin/env bash
# Bash scipt displaying "Best school" except for 4 and 8 position

counter=0
while [ $counter -lt 10 ]
do
  if [ $counter -eq 3 ]
  then
    echo "bad luck"
  elif [ $counter -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
    
  fi
    (( counter++ ))
done
